{{- if and .Values.ingress.enabled (ne .Values.ingress.ingressController "ambassador") (not .Values.openshiftDeployment.enabled) (eq $.Values.common.searchEngine "elastic") -}}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- range $envType := $envTypeList -}}
{{- if ne $envType "share" }}
{{- $ingress_conf := $.Values.ingress.query.auth }}
{{- if eq $envType "live" }}
{{ $ingress_conf = $.Values.ingress.query.live }}
{{- end }}
{{- if or (not $.Values.storeWeb.enabled) (and (eq $envType "auth") (ne $ingress_conf.domain $.Values.ingress.reactstore.auth.domain)) (and (eq $envType "live") (ne $ingress_conf.domain $.Values.ingress.reactstore.live.domain)) }}
apiVersion: {{ $.Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}-query-ingress
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- if eq $.Values.ingress.ingressController "nginx" }}
    kubernetes.io/ingress.class: {{ default "nginx" $ingress_conf.ingressClass | quote }}
    {{- else if eq $.Values.ingress.ingressController "gke" }}
    kubernetes.io/ingress.class: {{ default "gce" $ingress_conf.ingressClass | quote }}
    {{- end }}
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- if eq $.Values.ingress.ingressController "nginx" }}
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.org/ssl-services: "{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}query-app"
    {{- end }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
spec:
  tls:
  - hosts:
    - {{ tpl ($ingress_conf.domain | toString) $ }}
    secretName: {{ default (printf "%s%s%s-certificate" $.Values.common.tenant $.Values.common.environmentName $envType) ($ingress_conf.tlsSecret) }}
  rules:
  - host: {{ tpl ($ingress_conf.domain | toString) $ }}
    http:
      paths:
      {{- if eq $.Values.ingress.apiVersion "networking.k8s.io/v1beta1" }}
      - path: {{- if eq $.Values.ingress.ingressController "nginx" }} / {{- else if eq $.Values.ingress.ingressController "gke" }} /* {{- end }}
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}query-app
          servicePort: 30901
      {{- else if eq $.Values.ingress.apiVersion "networking.k8s.io/v1" }}
      - path: {{- if eq $.Values.ingress.ingressController "nginx" }} / {{- else if eq $.Values.ingress.ingressController "gke" }} /* {{- end }}
        pathType: {{- if eq $.Values.ingress.ingressController "nginx" }} Prefix {{- else if eq $.Values.ingress.ingressController "gke" }} ImplementationSpecific {{- end }}
        backend:
          service:
            name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}query-app
            port:
              number: 30901
      {{- end }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}